//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statement
    {
        public long id { get; set; }
        public string text { get; set; }
        public Nullable<float> score { get; set; }
        public Nullable<System.DateTime> lastUpdated { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<long> occurrences { get; set; }
        public long channelId { get; set; }
    }
}
